### ISSUE TITLE
Hard coded path to config file in config class

### ISSUE THREAD

**Issue by drmarconi** [voxpupuli/puppet-graphite_powershell#4]
The configuration "file" resource has a hard coded path to "C:\GraphitePowershell", when the $install_dir parameter could specify an alternate installation directory.

Possibly change to:

`file { "${install_dir}/StatsToGraphiteConfig.xml":`

Thanks
L

**Comment by bastelfreak** [comment]
thanks for raising the issue. We're currently releasing a fixed version.
